import { AuditAction } from "@/generated/prisma/client";

// ─── Core Types ─────────────────────────────────────────────────────────────

export interface AuditContext {
  userId: string;
  userEmail: string | null;
  userRole: string | null;
  ipAddress: string | null;
  userAgent: string | null;
}

export interface ActivityLogData {
  userId: string;
  userEmail?: string | null;
  userRole?: string | null;
  action: AuditAction;
  entityType: string;
  entityId: string;
  description?: string | null;
  dataBefore?: Record<string, unknown> | null;
  dataAfter?: Record<string, unknown> | null;
  changedFields?: string[];
  ipAddress?: string | null;
  userAgent?: string | null;
}

// ─── HOF Configuration ─────────────────────────────────────────────────────

/**
 * Configuration for the withAuditLog() Higher-Order Function.
 *
 * @template TArgs - Tuple type representing the function's argument list
 * @template TResult - The function's return type
 */
export interface AuditLogConfig<TArgs extends unknown[], TResult> {
  /** The Prisma model name, e.g. "Product", "Order", "ChartOfAccount" */
  entityType: string;

  /** The mutation type */
  action: AuditAction;

  /**
   * Extracts the entity ID from the function's arguments.
   * For CREATE actions, return null — the ID will be extracted from the result.
   */
  getEntityId: (args: TArgs) => string | null;

  /**
   * Extracts the entity ID from the function's result (used for CREATE actions
   * where the ID is generated by the database).
   */
  getEntityIdFromResult?: (result: TResult) => string | null;

  /**
   * Fetches the full record BEFORE the mutation (for UPDATE/DELETE).
   * Should return null for CREATE actions.
   */
  fetchBefore?: (entityId: string) => Promise<Record<string, unknown> | null>;

  /**
   * Fetches the full record AFTER the mutation (for CREATE/UPDATE).
   * Should return null for DELETE actions.
   */
  fetchAfter?: (entityId: string) => Promise<Record<string, unknown> | null>;

  /**
   * Generates a human-readable description of the action.
   */
  describe?: (args: TArgs) => string;
}

// ─── Sensitive Field Constants ──────────────────────────────────────────────

/** Fields that must be stripped from JSONB snapshots before storage */
export const SENSITIVE_FIELDS = [
  "password",
  "accessToken",
  "refreshToken",
  "token",
  "secret",
  "bkashTrxId",
] as const;
